### ISSUE TITLE
[Feature request]: Add getter of fluid tank capacity to PlatformFluidItemHandler

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Botarium#11]
**`FluidContainer`** can get each tank capacity by **`getTankCapacity(int)`**.
But **`PlatformFluidItemHandler`** is can't. No getter of tank capacity in there.

So, When some code to do inserting fluid at item fully.
Inevitably, **`Long.MAX_VALUE`** must be used. (or Integer.MAX_VALUE)

In inside code of item, can solve it by declare method to return Literal or Config's value about capacity.
But outside of item, **no way to get capacity** for unified method.
In example, can't calculate fluid stored ratio.

So, i think need to add getter of fluid tank capacity to PlatformFluidItemHandler.

**Comment by CodexAdrian** [comment]
done in 1.7.12
