### ISSUE TITLE
[Bug]: Botarium causes RFTools Tablet to not work

### ISSUE THREAD

**Issue by togreglove** [terrarium-earth/Botarium#29]
### Bug Description

This bug is causing multiple packs to not be able to use the RFTools Tablet, not sure why

Cross posting issue here from McJty forums
https://github.com/McJtyMods/RFToolsStorage/issues/82

### Version

2.2.1

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
This is an RFtools issue they should **NOT** be setting the `BlockState` to null it is explicitly marked as NotNull in all locations, the gather capabilities event is still called even though the `BlockEntity` is not added to the world as it is ran in the base constructor for `BlockEntity` RFTools needs to supply a valid `BlockState` this will not only break Botarium but many other mods as that is not an intended result from `getBlockState` and is again explicitly marked to never happen as the method is marked as not null, the parameter of the constructor is also marked as not null, and the field is also marked as not null via a package info with `@ParametersAreNonnullByDefault`, `@MethodsReturnNonnullByDefault`, and `@FieldsAreNonnullByDefault`. RFTools needs to respect the expectations of these methods, and fields.

**Comment by togreglove** [comment]
thank you for your quick reply, I'll reference this back over there and hopefully he'll be able to get us back up and running!

**Comment by McJty** [comment]
@ThatGravyBoat can you tell me what exactly you mean? Which code of mine is setting blockstate to null?

**Comment by ThatGravyBoat** [comment]
> @ThatGravyBoat can you tell me what exactly you mean? Which code of mine is setting blockstate to null?

https://github.com/McJtyMods/RFToolsStorage/blob/1.20/src/main/java/mcjty/rftoolsstorage/modules/scanner/blocks/StorageScannerTileEntity.java#L145

**Comment by McJty** [comment]
Thanks. I'll fix that

**Comment by CodexAdrian** [comment]
Gonna close this then
