### ISSUE TITLE
[Bug]: Latest version o Botarium 1.19.2 1.9.1 too incompatible with IC2 classic!

### ISSUE THREAD

**Issue by 300f20t** [terrarium-earth/Botarium#32]
### Bug Description

Botarium does not work with IC2 Classic.

### How to Reproduce?

Place stone macerator.

### Expected Behavior

Compatibility with IC2 classic mod.

### Version

1.9.1

### Mod Loader Version

1.19.2-43.3.5

### Mod Loader

Forge

### Logs or additional context

https://bytebin.lucko.me/2GvNENY2eY

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Whatever the issue was it seems that its going to be fixed soon https://github.com/TinyModularThings/IC2Classic/issues/950
