### ISSUE TITLE
[Bug]: 1.20.4 NeoForge Crash on World loading 

### ISSUE THREAD

**Issue by MSandro** [terrarium-earth/Botarium#33]
### Bug Description

crash on loading a new world

### Expected Behavior

no crash

### Version

3.2.0

### Mod Loader Version

20.4.211

### Mod Loader

NeoForge

### Logs or additional context

crash-2024-03-25_13.36.15-server
https://pastebin.com/AgYq8Xs8

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Fixed in dev, 3.2.1 should fix it
