### ISSUE TITLE
[Bug]: crash when pressing E

### ISSUE THREAD

**Issue by Markus90MG** [terrarium-earth/Botarium#35]
### Bug Description

https://pastebin.com/pP99SY9k

### Version

2.3.3

### Mod Loader Version

1.20.1     47.2.30

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Dubstep34** [comment]
HUHU Deutsche Kartoffel-bock zu MODDEN? Das pack muss neu gepatched werden btw...

**Comment by CodexAdrian** [comment]
I responded to this issue in the discord, this issue is caused by Minecraft Transit Railway, a mod that causes a number of issues with other mods. Blockstates are never meant to be defined as null, hence this is an issue on their side.

**Comment by Yukifuri-Yukari** [comment]
when did MTR dev team fix it!!!
i must use MTR to make subways in  my city building!
