### ISSUE TITLE
[Bug]: Server Crashes after restart

### ISSUE THREAD

**Issue by Th3-Warfighter** [terrarium-earth/Botarium#36]
### Bug Description

When i shut down the server, and after some minutes i started again, the server crashes

### Version

2.3.4

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/bSr1ztR4

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Please report this to the Create: New Age repository
